---
title: 'R Graphics Cookbook: Chapter 4'
author: "Brandon Foltz"
date: "2023-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gcookbook)
```
```{r}
ggplot(BOD, aes(x = Time, y = demand)) +
  geom_line()
```

```{r}
BOD1 <- BOD
BOD1$Time <- factor(BOD1$Time)

# When the x variable is a factor, you must also use aes(group=1) to ensure that ggplot knows that the data points belong together and should be connected with a line. No space on the x-axis for 6.

ggplot(BOD1,
       aes(x = Time, y = demand, group = 1)) +
  geom_line()
```
```{r}
ggplot(BOD, aes(x = Time, y = demand)) +
  geom_line() +
  ylim(0, max(BOD$demand))

ggplot(BOD, aes(x = Time, y = demand)) +
  geom_line() +
  expand_limits(y = 0)
```
Add points

```{r}
ggplot(BOD, aes(x = Time, y = demand)) +
  geom_line() +
  geom_point()
```
```{r}
ggplot(worldpop,
       aes(x = Year, y = Population)) +
  geom_line() +
  geom_point()

ggplot(worldpop,
       aes(x = Year, y = Population)) +
  geom_line() +
  geom_point() +
  scale_y_log10()
```

Multiple Lines

```{r}
ggplot(tg, aes(x = dose, y = length, color = supp)) +
  geom_line()

ggplot(tg, aes(x = dose, y = length, linetype = supp)) +
  geom_line()

ggplot(tg, aes(x = factor(dose), y = length, color = supp, group = supp)) +
  geom_line()
```

```{r}
ggplot(tg, aes(x = dose, y = length, shape = supp)) +
  geom_line() +
  geom_point(size = 4)

ggplot(tg, aes(x = dose, y = length, fill = supp)) +
  geom_line() +
  geom_point(size = 4, shape = 21)
```

```{r}
ggplot(BOD,
       aes(x = Time, y = demand)) +
  geom_line(linetype = "dashed", size = 1, color = "blue")
```
```{r}
ggplot(tg, aes(x = dose, y = length, color = supp)) +
  geom_line() +
  scale_color_brewer(palette = "Set1")
```

Setting properties in and out of aes

```{r}
ggplot(tg,
       aes(x = dose, y = length, group = supp)) +
  geom_line(color = "darkgreen", size = 1.5)

ggplot(tg,
       aes(x = dose, y = length, color = supp)) +
  geom_line(linetype = "dashed") +
  geom_point(shape = 22, size = 3, fill = "white")
```

Change the appearance of points

```{r}
ggplot(BOD, aes(x = Time, y = demand)) +
  geom_line() +
  geom_point(size = 4, shape = 22, color = "darkred", fill = "pink")
```
```{r}
ggplot(BOD, aes(x = Time, y = demand)) +
  geom_line() +
  geom_point(size = 4, shape = 21, fill = "white")
```

```{r}
library(gcookbook)  
# Load gcookbook for the tg data set

# Save the position_dodge specification because we'll use it multiple times
pd <- position_dodge(0.2)

ggplot(tg, aes(x = dose, y = length, fill = supp)) +
  geom_line(position = pd) +
  geom_point(shape = 21, size = 3, position = pd) +
  scale_fill_manual(values = c("black","white"))
```
Shaded area
```{r}
sunspotyear <- data.frame(
  Year = as.numeric(time(sunspot.year)),
  Sunspots <- as.numeric(sunspot.year)
)

ggplot(sunspotyear, aes(x = Year, y = Sunspots)) +
  geom_area()

ggplot(sunspotyear, aes(x = Year, y = Sunspots)) +
  geom_area(color = "black", fill = "yellow", alpha = 0.2)

ggplot(sunspotyear, aes(x = Year, y = Sunspots)) +
  geom_area(fill = "yellow", alpha = 0.2) +
  geom_line()
```
Stacked Area

```{r}
ggplot(uspopage,
       aes(x = Year, y = Thousands, fill = AgeGroup)) +
  geom_area()

ggplot(uspopage, aes(x = Year, y = Thousands, fill = AgeGroup)) +
  geom_area(color = "black", size = 0.2, alpha = 0.4) +
  scale_fill_brewer(palette = "Blues")

ggplot(uspopage, aes(x = Year, y = Thousands, fill = AgeGroup, order = dplyr::desc(AgeGroup))) +
  geom_area(color = NA, alpha = 0.4) +
  scale_fill_brewer(palette = "Blues") +
  geom_line(position = "stack", size = 0.2)
```

Proportional Stacked Area

```{r}
ggplot(uspopage,
       aes(x = Year, y = Thousands, fill = AgeGroup)) +
  geom_area(position = "fill", color = "black", size = 0.2, alpha = 0.4) +
  scale_fill_brewer(palette = "Blues")

ggplot(uspopage, aes(x = Year, y = Thousands, fill = AgeGroup)) +
  geom_area(position = "fill", colour = "black", size = .2, alpha = .4) +
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(labels = scales::percent)
```

Confidence Region

```{r}
climate_mod <- climate|>
  filter(Source == "Berkeley")|>
  select(Year, Anomaly10y, Unc10y)
climate_mod

ggplot(climate_mod,
       aes(x = Year, y = Anomaly10y)) +
  geom_ribbon(aes(ymin = Anomaly10y - Unc10y, ymax = Anomaly10y + Unc10y), alpha = 0.2) +
  geom_line()

# With a dotted line for upper and lower bounds
ggplot(climate_mod, aes(x = Year, y = Anomaly10y)) +
  geom_line(aes(y = Anomaly10y - Unc10y), colour = "grey50", linetype = "dotted") +
  geom_line(aes(y = Anomaly10y + Unc10y), colour = "grey50", linetype = "dotted") +
  geom_line()
```

