---
title: 'R Graphics Cookbook: Chapter 11'
author: "Brandon Foltz"
date: "2023-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
mpg_plot <- ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point()

mpg_plot +
  facet_grid(. ~ cyl)

mpg_plot +
  facet_grid(drv ~ .)

mpg_plot +
  facet_grid(drv ~ cyl)

mpg_plot +
  facet_wrap(~class)

mpg_plot +
  facet_wrap(~ class, nrow = 2)

mpg_plot +
  facet_wrap(~ class, ncol = 4)
```

Using Facets with Different Axes

```{r}
mpg_plot <- ggplot(mpg, aes(x  = displ, y = hwy)) +
  geom_point()

mpg_plot +
  facet_grid(drv ~ cyl, scales = "free_y")

mpg_plot +
  facet_grid(drv ~ cyl, scales = "free")
```

Changing the Text of Facet Labels

```{r}
mpg_mod <- mpg|>
  mutate(drv = recode(drv, "4" = "4wd", "f" = "Front", "r" = "Rear"))

ggplot(mpg_mod, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ .)
```

```{r}
ggplot(mpg_mod, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ .)
```

```{r}
ggplot(mpg_mod, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ ., labeller = label_both)
```

```{r}
# Make a modified copy of the original data
mpg_mod <- mpg %>%
  mutate(drv = recode(drv,
    "4" = "4^{wd}",
    "f" = "- Front %.% e^{pi * i}",
    "r" = "4^{wd} - Front"
  ))

ggplot(mpg_mod, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ ., labeller = label_parsed)
```

```{r}
library(gcookbook)  # Load gcookbook for the cabbage_exp data set

ggplot(cabbage_exp, aes(x = Cultivar, y = Weight)) +
  geom_col() +
  facet_grid(. ~ Date) +
  theme(
    strip.text = element_text(face = "bold", size = rel(1.5)),
    strip.background = element_rect(fill = "lightblue", colour = "black", size = 1)
  )
```

